const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'})
require( "dotenv" ).config();
const { SWAGGER_HOST } = process.env;

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: SWAGGER_HOST,
    basePath: "/api",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    securityDefinitions: {
        bearerAuth: {
            type: "http",
            scheme: "bearer",
            bearerFormat: 'JWT'
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
})