version: '2'

services:

  app:
    image: node:16
    container_name: app
    depends_on:
      - "db"
      - "redis"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3001/ || exit 1
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
    volumes:
      - ./www/backend:/var/www/backend
    networks:
      vps-ikram-network:
        ipv4_address: 192.168.10.10
    command: bash -c "cd /var/www/backend && npm i && npm run db:reset && npm run swagger-autogen"

  db:
    image: postgres
    container_name: database
    restart: always
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
    logging:
      options:
        max-size: 10m
        max-file: '3'
    networks:
      vps-ikram-network:
        ipv4_address: 192.168.10.11
    volumes:
      - ./database/data:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    mem_limit: 256m
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      vps-ikram-network:
        ipv4_address: 192.168.10.12

networks:
  vps-ikram-network:
    name: vps-ikram-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1